# Generated by Django 3.2 on 2022-03-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cities', '0002_auto_20220312_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymodel',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
