# Generated by Django 3.2 on 2022-03-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cities', '0003_alter_citymodel_options'),
        ('app_trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название маршрута')),
                ('travel_time', models.PositiveSmallIntegerField(verbose_name='Время в пути')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_arrival_city_set', to='app_cities.citymodel', verbose_name='Город прибытия')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_departure_city_set', to='app_cities.citymodel', verbose_name='Город отправления')),
                ('trains', models.ManyToManyField(to='app_trains.TrainModel', verbose_name='Список поездов')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'ПМаршруты',
                'ordering': ['travel_time'],
            },
        ),
    ]
