# Generated by Django 3.2 on 2022-05-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routemodel',
            options={'ordering': ['travel_time'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
    ]
